remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
minima:
  skin: auto
title: The (SecOps) Feed
description: The Feed is a curated Open-Source Operational Threat Intelligence for SOC / DFIR / CTI and Threat Hunting Teams.
author: Ruslan Rustchev